### ISSUE TITLE
IllegalArgumentException in AiroMem after updating from v1.0.2 to v1.0.3

### ISSUE THREAD

**Issue by McPringle** [airomem/airomem#5]
```
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at pl.setblack.airomem.core.builders.PrevaylerBuilder.createPrevayler(PrevaylerBuilder.java:122)
	at pl.setblack.airomem.core.builders.PrevaylerBuilder.build(PrevaylerBuilder.java:75)
	at pl.setblack.airomem.core.builders.PersistenceFactory.load(PersistenceFactory.java:35)
	at pl.setblack.airomem.core.builders.PersistenceFactory.initOptional(PersistenceFactory.java:66)
	at pl.setblack.airomem.core.SimpleController.loadOptional(SimpleController.java:41)
	at ch.sportchef.business.PersistenceManager.createSimpleController(PersistenceManager.java:45)
```
Here is my whole `console.log` file including the stack trace:
https://gist.github.com/McPringle/fc3a5e74412d4e540600

**Comment by jarekratajski** [comment]
I have this bug when I still have old files in bin folder of jboss. 
So quick fix is to remove them or move to the user folder. 

Real fix... still has to be done.

**Comment by McPringle** [comment]
Thanks for your hint, that solved our problem. Should we close this issue or should it remain open until the real fix is done?

**Comment by jarekratajski** [comment]
It should be open. It is still a bug.
